title: "Swiss ISA Hub"
description: "Non-profit association in Switzerland."
url: "https://swissisahub.org"
baseurl: ""
lang: en-GB
timezone: Europe/Zurich

theme: minima

header_pages:
  - about.md
  - members.md
  - contacts.md

logo: /assets/images/logo_isa_hub.png


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-remote-theme

permalink: /:categories/:title/
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo

minima:
  skin: auto
  social_links:
    - platform: github
      user_url: "https://github.com/tbd"
    - platform: linkedin
      user_url: "https://www.linkedin.com/company/tbd"
  date_format: "%-d. %B %Y"
show_excerpts: true

exclude:
  - README.md
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - .github
  - scripts
